trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CYPRESS_baseUrl: 'https://automationexercise.com'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Setup Node.js'

  - script: |
      npm ci
      npm run test:ci
    displayName: 'Install dependencies & run Cypress tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'results'
      artifactName: 'cypress-results'
