name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test:ci

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: results

      - name: Trigger Azure DevOps Pipeline
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_PIPELINE_ID: ${{ secrets.AZURE_PIPELINE_ID }}
          AZURE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}
        run: npm run trigger:azure
