name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js 16
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # 3️⃣ Cache node modules
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-16-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5️⃣ Run Cypress CI tests (headless + reports)
      - name: Run Cypress CI tests
        run: npm run test:ci

      # 6️⃣ Upload artifacts
      - name: Upload Mochawesome HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: results/mochawesome/html/*.html

      - name: Upload Mochawesome JSON reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-json
          path: results/mochawesome/*.json

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload downloads (e.g., invoices)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-downloads
          path: cypress/downloads
